## 测试环境 端口号
server:
  port: 9999

## mySql数据源 - 配置信息
#  采用德鲁伊连接池
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staging?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 18
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM dual


